services:
  postgres:
    image: postgres:16
    container_name: orders-api-postgres
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_password
    ports:
      - "5432:5432"
    volumes:
      - orders_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orders_user -d orders_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  floci:
    image: floci/floci:latest
    container_name: orders-api-floci
    ports:
      - "4566:4566"

  app:
    build: .
    container_name: orders-api-app
    depends_on:
      postgres:
        condition: service_healthy
      floci:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orders_db
      SPRING_DATASOURCE_USERNAME: orders_user
      SPRING_DATASOURCE_PASSWORD: orders_password
      JWT_SECRET: "orders-api-jwt-secret-1234567890-orders-api-jwt-secret-1234567890"
      JWT_EXPIRATION_MINUTES: 60

      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_S3_BUCKET: orders-api-files
      AWS_S3_ENDPOINT: http://floci:4566
    ports:
      - "8080:8080"

volumes:
  orders_postgres_data: