spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: orders_user
    password: orders_password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true